pre-commit:
  parallel: true
  jobs:
    - name: Knip
      run: npx knip --strict --cache
    - name: ESLint
      run: npx eslint --cache --concurrency auto

commit-msg:
  parallel: true
  jobs:
    - name: commitlint
      run: npx commitlint --edit $1

check:
  parallel: true
  jobs:
    - name: Knip
      run: npx knip --strict --cache
    - name: ESLint
      run: npx eslint --cache --concurrency auto

fix:
  jobs:
    - name: Knip
      run: npx knip --strict --cache --fix
    - name: ESLint
      run: npx eslint --fix --cache --concurrency auto
