pre-commit:
  parallel: true
  jobs:
    - name: ESLint
      run: npx eslint --cache --concurrency auto
    - name: Knip
      run: npx knip --strict --cache

commit-msg:
  parallel: true
  jobs:
    - name: commitlint
      run: npx commitlint --edit $1

build:
  jobs:
    - name: TypeScript
      run: npx tsc -b

check:
  parallel: true
  jobs:
    - name: ESLint
      run: npx eslint --cache --concurrency auto
    - name: Knip
      run: npx knip --strict --cache

fix:
  jobs:
    - name: Knip
      run: npx knip --strict --cache --fix
    - name: ESLint
      run: npx eslint --fix --cache --concurrency auto
