pre-commit:
  parallel: true
  jobs:
    - name: ESLint
      run: npx eslint --cache --concurrency auto
    - name: Knip
      run: npx knip --strict

commit-msg:
  parallel: true
  jobs:
    - name: commitlint
      run: npx commitlint --edit $1

check:
  parallel: true
  jobs:
    - name: ESLint
      run: npx eslint --cache --concurrency auto
    - name: Knip
      run: npx knip --strict

fix:
  jobs:
    - name: Knip
      run: npx knip --strict --fix
    - name: ESLint
      run: npx eslint --fix --cache --concurrency auto
